### ISSUE TITLE
New Feature: "Delete this track from disk"

### ISSUE THREAD

**Issue by vovan888** [kartik-venugopal/aural-player#34]
This feature could be useful when sorting out unneeded music from a folder.

**Comment by maculateConception** [comment]
@vovan888

Hi, thanks for your suggestion.

I guess that could be a useful feature, but also it may be risky. Generally, deleting files tends to be risky ... people may complain that they've lost their files because of the app. That's why I'm not so sure about this one.

Currently, what users could do is - Right-click on a track, click "Show in Finder" ... that will open and select the file in Finder, within its enclosing folder, and there the user could do the cleanup / sorting out you speak of.

Is that a good enough solution, you think ?

**Comment by vovan888** [comment]
> but also it may be risky.

This feature could be explicitly enabled in the settings with default to OFF. 

> Currently, what users could do is - Right-click on a track, click "Show in Finder" ... that will open and select the file in Finder, within its enclosing folder, and there the user could do the cleanup / sorting out you speak of.

That is exactly what I do. But it is not that convenient...

**Comment by maculateConception** [comment]
Ok, thanks. I will think about it for the next release.

If I do end up implementing it, it will need to have a confirmation prompt - "Are you sure you wish to delete the selected file(s) ?", perhaps with a "Move to Trash" option as well.

**Comment by vovan888** [comment]
Ok, thank you!

>  with a "Move to Trash" option as well.

Great idea! Moving to trash is safer and should be always used.

**Comment by kartik-venugopal** [comment]
I have second thoughts about implementing this feature. 

I think this is a file system management feature and I don't want the app to be bloated with unrelated features, so I'm closing this one.
