### ISSUE TITLE
Improve Cue Sheet support

### ISSUE THREAD

**Issue by rain84** [kartik-venugopal/aural-player#52]
Could you add support of .cue -playlists, please?

**Comment by kartik-venugopal** [comment]
Sounds good. Added to the TODO list !

**Comment by kartik-venugopal** [comment]
Can you please share with me an example .cue playlist file ? That will help me in developing this feature and testing it. Thanks !

**Comment by rain84** [comment]
@kartik-venugopal , shure!

Here is it ⤵️
[Tool - Fear Inoculum [SICP-6231] FLAC.cue](https://drive.google.com/file/d/11dkJ7BgCQCM1AMAoAs7P81zv64QJZ2Hx/view?usp=sharingl)

**Comment by kartik-venugopal** [comment]
Hey @rain84, thanks for sharing the CUE sheet. If you don't mind, could you also please share the audio file with me ? That way, I will be able to completely test this new feature. I am trying to develop it right now.

Thanks !

**Comment by rain84** [comment]
I can not share audio file, because it will be illegal distribution of multimedia data.
But you can easily find such files on the almost any torrent trackers.

**Comment by theramzay** [comment]
Hello @kartik-venugopal, your player is AWESOME, but it really miss `CUE`. Any progress on this feature? Thanks!

**Comment by kartik-venugopal** [comment]
Hey @theramzay , thanks! Yes, I did recently resume work on this feature. I will try to put it out soon and let you know.

**Comment by kartik-venugopal** [comment]
I have released this feature in a new build titled "preview4" ... you can get it from the latest release page.

Let me know if it works / doesn't work for you.

Cheers!

**Comment by LesterJitsi** [comment]
Always for sake of feedback report, it works for me with one minor caveat. The .cue file provided by @theramzay works fine, however .cue files found in the wild very often use a different naming scheme. I'm attaching a couple which Aural can't open, but Pine Player, e.g., has no trouble with. I've edited one to make it work with Aural (attached too: I substituted the file extension). I'm attaching the support folder too, created just before trying to open .m3u and .cue so you can check the log.

In short, I don't know if it's worth but adding an "export as .cue file" item to the _Play Queue_ menu would prevent reports of issues. I have tons of .cue files that Aural can't open. Cue files are inherently pesky and I gave up on them in favour of .m3u. Just as an example, if you're editing one and your text editor has the brilliant idea of using smart quotes it won't work. With TextEdit you have to remember to save it as .txt and rename as .cue... a pain.
[aural.zip](https://github.com/user-attachments/files/16564837/aural.zip)
[cuefiles.zip](https://github.com/user-attachments/files/16564838/cuefiles.zip)

**Comment by kartik-venugopal** [comment]
Hey @LesterJitsi, thanks for the info and the sample cue files. I have never used them, so I was only able to use a small handful of samples I found online and also from what I understand, some of the metadata in cue files is used for CD ripping, not for playback. If the files have a weird structure, Aural won't be able to open them.

In any case, I will take a look at some of your files and see if I can improve the cue support in Aural. But I can't promise too much, because this is a feature that I simply do not use myself and I just don't have the knowledge to make it perfect.

Cheers!

**Comment by kartik-venugopal** [comment]
BTW, when you say can't open, what exactly do you mean ? Do you mean the files are not added to the Play Queue ? Or does the app crash / freeze ? Some more details would help.

**Comment by LesterJitsi** [comment]
> BTW, when you say can't open, what exactly do you mean ?

Simply the files are not added to the queue, the app just seems to shudder but doesn't freeze or crash. Most likely you're seeing no record in the attached log.

> Is this expected to work with cue files ? Player apps guessing the file extension ?

So it seems. As I said apps like Pine Player have no problem at guessing, BUT you'll see a single item with a drop-down menu (see this .cue with no reference to actual .flac files):
![Screenshot 2024-08-10 alle 15 56 13_1](https://github.com/user-attachments/assets/a93d8847-293f-4e89-8036-f744775081bb)

The wide difference among .cue files appears to be related to the app used for ripping the CD/Album. AFAIK, the scheme used by X Lossless Decoder works fine for Mac, you can create .cue for a single track or split tracks:
[https://tmkk.undo.jp/xld/index_e.html](url)

The file provided by @theramzay appears a single long .flac ripped from CD or Album with ExactAudioCopy without splitting.

TBH, it would be easier to re-create and export .cue files with Aural with actual file extensions when a user happens to play a queue, rather than make a work of guessing. Just my 2 cents, as most users won't appreciate having to substitute lots of .cue files ready for use. I repeat I don't use them anymore.

**Comment by kartik-venugopal** [comment]
Thanks again for the info.

So the way Aural sees it, there are 2 main scenarios (in terms of CUE file structure)

1. One FILE, multiple TRACKs (in Aural, this manifests as a single track but with multiple chapters ... see screenshot below)
2. Multiple FILEs, each with one TRACK ... this will appear in Aural just as multiple tracks with no particular indication that they came from a CUE file (just as with M3U).

All this said, I will do the following (perhaps not immediately, but for the main release) ...

1. As you requested, add the ability to export from Aural as .cue
2. Add the ability to guess file extensions (but they have to have the same file name minus the extension, or this will not work).
3. Long-term: I will probably use a proper CUE parsing library like libcue instead of writing the CUE parsing logic myself ... this will extend support to be able to handle a larger variety of CUE files in the wild.

Hope this is good enough! Wish I knew more about CUE 😄 

This is what scenario 1 looks like in Aural (single track, multiple chapters):

![cueExample](https://github.com/user-attachments/assets/901c67a5-e1f0-4948-9a35-b2e77663fc90)

**Comment by kartik-venugopal** [comment]
PS - Just one more thing, since you may not be aware.

I noticed that Pine Player displays the CUE sheet as one item in the queue ... this would be quite challenging to achieve in the Play Queue in Aural Player (without significant restructuring of the code), BUT you will be able to see something similar in the new **_Library_** ... the Library basically scans your entire music collection (in the ~/Music folder) and shows a nicely organized view with all your files, organized as albums, genres, artists, decades, and playlists (including CUE)

So, in the near future, you would be able to look at your new library in Aural and just play your CUE files directly from there with one click 😉 

🤞

**Comment by LesterJitsi** [comment]
> I noticed that Pine Player displays the CUE sheet as one item in the queue ... this would be quite challenging to achieve in the Play Queue in Aural Player

NO PROBLEM AT ALL. IMHO,that's a bug not a feature. And I'm just reporting feedback, I didn't ask support for .cue files 😉 

> Long-term: I will probably use a proper CUE parsing library like libcue instead of writing the CUE parsing logic myself ... this will extend support to be able to handle a larger variety of CUE files in the wild.

This makes perfectly sense 👍

**Comment by kartik-venugopal** [comment]
The requested improvements (except export to Cue, which seems not worthwhile, given it's now able to guess file extensions) have been implemented ... closing the issue.
