### ISSUE TITLE
Autoplay enhancement

### ISSUE THREAD

**Issue by LesterJitsi** [kartik-venugopal/aural-player#58]
Hi, I do hope you don’t hate me for finding a new little bug 😇  Nothing urgent at all.
In short, autoplay seems to behave inconsistently. My playback preferences are:

![playback pref](https://github.com/kartik-venugopal/aural-player/assets/25617355/a22ccb7d-683b-42f1-86f1-5dd48da36d1e)

Aural is my default app to open .m3u files.  Autoplay does not work as expected when you double click a .m3u file: no matter what you check in playback preferences (see screens below), even though a track is currently playing, Aural jumps to the first added track and starts to play it. The same happens when you add the .m3u file by “open with”, but NOT if you add it by drag and drop: then autoplay works as expected.

![autoplay1](https://github.com/kartik-venugopal/aural-player/assets/25617355/946ecd5d-6a46-46da-8382-4023d9cb7bb9)

![autoplay2](https://github.com/kartik-venugopal/aural-player/assets/25617355/e99bab16-5d18-4c8d-be59-7c887b163101)

A different issue I mention here is that accessory dialog windows are now non-modal but playback shortcuts controls continue to work even when one dialog is active. Maybe this is a feature and not a bug, but it takes you aback when you use the keyboard and a  dialog is open. It’s not standard Mac application behavior.

Please bear with me. Thanks.

**Comment by kartik-venugopal** [comment]
If I'm honest, it's bug reports like yours that make this app better, so no worries at all. I actually appreciate it a lot !

I will check out both issues. 

To be clear, regarding the 2nd issue, are you talking about the playback controls like Space and Cmd + arrow ? i.e. shortcut keys that are in the Playback menu ? Or are you talking about the standard Mac media keys on your keyboard like the play / seek buttons ?

**Comment by kartik-venugopal** [comment]
One more thing, Lester ... you may not be aware of some new options (and hence, new playlist behavior) that was fairly recently added to Aural ... they specifically affect playlist (and indirectly, playback) behavior for drag/drop and "Open With". 

I have a feeling that those new options are affecting your playlist behavior in some way, because you mentioned the difference between drag/drop and "Open With".

Can you do me a small favor, please ? In your Preferences window, can you go to the Playlist tab, take a screenshot, and send it to me ? Thanks ! 

See the image below ... this is the preferences pane I'd like to see.

<img width="712" alt="Screenshot 2023-05-30 at 11 15 10 PM" src="https://github.com/kartik-venugopal/aural-player/assets/30028539/c803c8bc-0d49-4ad4-aa6f-e656b0b5423c">

**Comment by kartik-venugopal** [comment]
Hi Lester, after a bit of investigation, it is clear to me why Aural behaves the way it does when you double-click or "Open With". It is as designed, because, to me, the semantics of the double-click or "Open With" user action imply that the user wants to play that item immediately, regardless of what options he may have set in the app preferences. Think of the double-click or "Open With" action as "overriding" the behavior defined in the preferences. It's a special case, and hence, the autoplay options don't really apply ... this is how it was designed.

If you look at most other players (Winamp, which is what Aural was largely modeled after, VLC, etc) ... they will always immediately play any files opened with a double-click or "Open With". So this is what was decided as the behavior for Aural as well.

That said, let me ask this - As a user of the app, what do you intend to do when you double-click or "Open With" ? 

1 - Do you see this as a add operation equivalent to drag/drop or clicking the + (Add) button within the app ? 
2 - Or do you prefer to play immediately ?
3 - Or do you prefer to be given a choice of what to do ? (in the app preferences ... this would probably be a separate new option, not the same as the existing autoplay options).

If you feel that you'd like to choose the action, let me know, and I will think of how to implement it.

Cheers !

**Comment by LesterJitsi** [comment]
Thank you for your blazing fast replies. My Playlist preference tab:

![playlisttab](https://github.com/kartik-venugopal/aural-player/assets/25617355/69d268e7-e081-4b32-8684-735013fd98d5)

Yes, I was aware of the recent new options about drag and drop and "Open with". 

> It is as designed, because, to me, the semantics of the double-click or "Open With" user action imply that the user wants to play that item immediately, regardless of what options he may have set in the app preferences. 

This does make sense. As a user, I prefer to start with empty playlist and having full control over what is playing. So to me the handiest way to add tracks is double clicking the .m3u file pertaining to one CD or folder of tracks. I may add more than one without expecting them to start playing. Of course this is a very personal choice, I'd rather double click than drag'n'drop because I use Yoink and I've to press and hold the fn key in order not to have its automatic shelf in the way (extremely useful otherwise). "Open with" is the less attractive for me. So my answer to your question would be 1), to me is an add operation. The best would be 3) having a choice of what to do, but I'm afraid this way of proceeding may overburden the Preferences window in the long run.

I understand it's designed to be this way and I can live with it.

> To be clear, regarding the 2nd issue, are you talking about the playback controls like Space and Cmd + arrow ? i.e. shortcut keys that are in the Playback menu ?

Yes. If you have Aural playing a track and you open whatever accessory dialog window, you can stop-restart playback pressing Space. All Playback menu controls work with a dialog open. BUT, I just realized, if you leave the dialog open and click on Aural main window to make it active, Space doesn't work anymore (the remaining controls from Playback menu still do). Space gets back to work when the dialog window is in the forefront. AND Space keep working if you switch between dialog and main window using the default Mac shortcut ⌘' instead of clicking.
If you make the main window active by clicking on it (Vertical full stack), you can still stop-restart playback clicking controls in Player's window.

Thank you!

**Comment by kartik-venugopal** [comment]
An update, @LesterJitsi - I mostly implemented the feature you asked for, but ran into a special case that requires more careful consideration. So, this may take me some time to sort out.

Just FYI.

**Comment by kartik-venugopal** [comment]
Hi @LesterJitsi , so sorry this has taken so long to implement - it was a bit tricky to implement the autoplay enhancement you requested. But I have come up with an implementation of it ... I am not sure if it has any unintended side effects, but please try it out and let me know what you think ... I have not had much time to test it thoroughly.

[v3.22.0](https://github.com/kartik-venugopal/aural-player/releases/tag/v3.22.0)

BTW, I have not had a chance to look into the other issue you mentioned - about the playback shortcuts ... so I will keep this issue open till I resolve that issue as well (hopefully soon).

As always, thanks for supporting my app. Cheers ! 👍

**Comment by LesterJitsi** [comment]
Hi @kartik-venugopal , definitely no problem to wait a bit when it's worth 😉  Thank you very much, I'm going to test it some more, but it seems to work as expected at first glance.

> BTW, I have not had a chance to look into the other issue you mentioned - about the playback shortcuts

This issue appears to be solved. In the meantime I had to upgrade from Mojave to Ventura on Intel, so I can't say whether it's solved on Mojave too. Once again, thank you!
